import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import BackgroundSound from "./components/BackgroundSound";
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Emeka Victor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <BackgroundSound />
        {children}
      </body>
    </html>
  );
}
